.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TIMR\-POP" "1" "April 2017" "FOX21.at" "Timr Manual"
.
.SH "NAME"
\fBtimr\-pop\fR \- Pop current Track from the Stack\.
.
.SH "SYNOPSIS"
timr pop [\fIoptions\fR]
.
.SH "DESCRIPTION"
Stop and pop the current running Track from the Stack\. Also \fBtimr stop\fR removes the current Track from the Stack\.
.
.SH "TRACK OPTIONS"
.
.TP
\-d, \-\-date \fIdate\fR
End Date for the current running Track, Start Date for the next underlying Track to continue\. Same applies for \fB\-\-time\fR\.
.
.TP
\-t, \-\-time \fItime\fR
Same logic as for \fB\-\-date\fR option but for Time\.
.
.SH "GENERAL OPTIONS"
.
.TP
\-h, \-\-help
Displays the help page\.
.
.SH "EXAMPLES"
.
.SH "DATETIME FORMATS"
.
.TP
\fIdate_time\fR
A DateTime is one single string representing \fB<date> <time>\fR\.
.
.TP
\fIdate\fR
Formats: \fBYYYY\-MM\-DD\fR, \fBMM/DD/YYYY\fR, \fBDD\.MM\.YYYY\fR
.
.TP
\fItime\fR
Formats: \fBHH:MM\fR, \fBHH:MM:SS\fR
.
.SH "ONLINE RESCOURCES"
.
.IP "\(bu" 4
Homepage \fIhttps://timr\.fox21\.at/\fR
.
.IP "\(bu" 4
Code Coverage \fIhttps://timr\.fox21\.at/coverage/\fR
.
.IP "\(bu" 4
GitHub Page \fIhttps://github\.com/TheFox/timr\fR
.
.IP "\(bu" 4
RubyGems Page \fIhttps://rubygems\.org/gems/timr\fR
.
.IP "\(bu" 4
Travis CI Repository \fIhttps://travis\-ci\.org/TheFox/timr\fR
.
.IP "" 0
.
.SH "BUGS"
Report bugs to
.
.IP "\(bu" 4
the GitHub issues tracker \fIhttps://github\.com/TheFox/timr/issues\fR
.
.IP "\(bu" 4
or via email to \fIchristian@fox21\.at\fR\.
.
.IP "" 0

