.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TIMR\-PUSH" "1" "April 2017" "FOX21.at" "Timr Manual"
.
.SH "NAME"
\fBtimr\-push\fR \- Push new Track to the Stack\.
.
.SH "SYNOPSIS"
timr push [\fIoptions\fR] [\fItask_id\fR [\fItrack_id\fR]]
.
.SH "DESCRIPTION"
Sometimes you need to work on a Task only temporary\. You want to track the time for this as well\. For example fixing a bug\. When you fixed the bug you want to continue your actual work\. Here comes \fBpush\fR and \fBpop\fR into the game\. It modifies the Stack\. If you \fBpush\fR a new Track the below Track will be paused and hold on the Stack\. On \fBpop\fR the current Track (Top Track) will be stopped and the next below will continue\.
.
.SH "OPTIONS"
See timr\-start(1)\.
.
.SH "ARGUMENTS"
See timr\-start(1)\.
.
.SH "DATETIME FORMATS"
.
.TP
\fIdate_time\fR
A DateTime is one single string representing \fB<date> <time>\fR\.
.
.TP
\fIdate\fR
Formats: \fBYYYY\-MM\-DD\fR, \fBMM/DD/YYYY\fR, \fBDD\.MM\.YYYY\fR
.
.TP
\fItime\fR
Formats: \fBHH:MM\fR, \fBHH:MM:SS\fR
.
.P
See \fBtimr\-task(1)\fR, section ESTIMATION for estimation \fItime\fR details\.
.
.SH "ONLINE RESCOURCES"
.
.IP "\(bu" 4
Homepage \fIhttps://timr\.fox21\.at/\fR
.
.IP "\(bu" 4
Code Coverage \fIhttps://timr\.fox21\.at/coverage/\fR
.
.IP "\(bu" 4
GitHub Page \fIhttps://github\.com/TheFox/timr\fR
.
.IP "\(bu" 4
RubyGems Page \fIhttps://rubygems\.org/gems/timr\fR
.
.IP "\(bu" 4
Travis CI Repository \fIhttps://travis\-ci\.org/TheFox/timr\fR
.
.IP "" 0
.
.SH "BUGS"
Report bugs to
.
.IP "\(bu" 4
the GitHub issues tracker \fIhttps://github\.com/TheFox/timr/issues\fR
.
.IP "\(bu" 4
or via email to \fIchristian@fox21\.at\fR\.
.
.IP "" 0

