.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TIMR\-TASK" "1" "April 2017" "FOX21.at" "Timr Manual"
.
.SH "NAME"
\fBtimr\-task\fR \- Show, add, edit, or remove a Task\.
.
.SH "SYNOPSIS"
timr task [show] [\fIoptions\fR] [\fItask_id\fR\.\.\.]
.
.P
timr task add [\fIoptions\fR]
.
.P
timr task set [\fIoptions\fR] \fItask_id\fR
.
.P
timr task remove \fItask_id\fR\.\.\.
.
.SH "DESCRIPTION"
This command takes several subcommands\. Per default, when providing a Task ID it displays details about this specific Task\. Without any arguments it lists all Tasks\.
.
.SH "SUBCOMMANDS"
.
.TP
add
Add a new Task\.
.
.TP
set
Edit an existing Task\.
.
.TP
show
Default when not providing a specific subcommand\.
.
.TP
remove
Delete a Task, all informations about this Task and all including Tracks\. This cannot be undone\.
.
.SH "ADD/SET OPTIONS"
.
.TP
\-n, \-\-name \fIname\fR
Task Name\.
.
.TP
\-\-desc, \-\-description \fIstr\fR
Task Description\.
.
.TP
\-e, \-\-est, \-\-estimation \fItime\fR
Task Estimation\. See details below\.
.
.TP
\-b, \-\-billed
Mark Task as billed\.
.
.TP
\-\-unbilled
Mark Task as unbilled\.
.
.TP
\-r, \-\-hourly\-rate \fIvalue\fR
Set the Hourly Rate\.
.
.TP
\-\-no\-hourly\-rate
Unset Hourly Rate\.
.
.TP
\-\-fr, \-\-flat\-rate, \-\-flat
Has Task a Flat Rate?
.
.TP
\-\-no\-flat\-rate, \-\-no\-flat
Unset Flat Rate\.
.
.SH "SHOW OPTIONS"
.
.TP
\-t, \-\-tracks
Show a list of Track IDs for each Task\.
.
.SH "GENERAL OPTIONS"
.
.TP
\-h, \-\-help
Displays the help page\.
.
.SH "EXAMPLES"
.
.nf

timr task
timr task abcd12
timr task show abcd12
timr task set \-\-name \'task_x\' \-\-estimation \'2h 30m\'
timr task set \-\-billed \-\-hourly\-rate 50 \-\-flat\-rate abcd12
timr task set \-\-unbilled \-\-no\-hourly\-rate \-\-no\-flat\-rate abcd12
timr task add \-\-name \'task_z\' \-\-estimation 4h \e
    \-\-hourly\-rate 50 \-\-flat\-rate
timr task remove abcd12
.
.fi
.
.SH "MAN UNITS"
.
.IP "\(bu" 4
8 hours are 1 man\-day\.
.
.IP "\(bu" 4
5 man\-days are 1 man\-week, and so on\.
.
.IP "" 0
.
.SH "ESTIMATION"
Estimation is parsed by chronic_duration\.
.
.P
Examples:
.
.IP "\(bu" 4
\fB\-e 2:10:5 # Sets Estimation to 2h 10m 5s\.\fR
.
.IP "\(bu" 4
\fB\-e \'2h 10m 5s\' # Sets Estimation to 2h 10m 5s\.\fR
.
.IP "" 0
.
.P
Use \'+\' or \'\-\' to calculate with Estimation Times:
.
.IP "\(bu" 4
\fB\-e \'\-45m\' # Subtracts 45 minutes from the original Estimation\.\fR
.
.IP "\(bu" 4
\fB\-e \'+1h 30m\' # Adds 1 hour 30 minutes to the original Estimation\.\fR
.
.IP "" 0
.
.P
See chronic_duration for more examples\. https://github\.com/henrypoydar/chronic_duration
.
.SH "BILLED/UNBILLED"
Set a Task as \fBbilled\fR or \fBunbilled\fR to know which Task you already billed a client\.
.
.P
If a whole Task gets billed/unbilled all Tracks are changed to billed/unbilled\. Each Track has a flag \fBis_billed\fR\.
.
.SH "DATETIME FORMATS"
.
.TP
\fIdate_time\fR
A DateTime is one single string representing \fB<date> <time>\fR\.
.
.TP
\fIdate\fR
Formats: \fBYYYY\-MM\-DD\fR, \fBMM/DD/YYYY\fR, \fBDD\.MM\.YYYY\fR
.
.TP
\fItime\fR
Formats: \fBHH:MM\fR, \fBHH:MM:SS\fR
.
.P
See \fBtimr\-task(1)\fR, section ESTIMATION for estimation \fItime\fR details\.
.
.SH "ONLINE RESCOURCES"
.
.IP "\(bu" 4
Homepage \fIhttps://timr\.fox21\.at/\fR
.
.IP "\(bu" 4
Code Coverage \fIhttps://timr\.fox21\.at/coverage/\fR
.
.IP "\(bu" 4
GitHub Page \fIhttps://github\.com/TheFox/timr\fR
.
.IP "\(bu" 4
RubyGems Page \fIhttps://rubygems\.org/gems/timr\fR
.
.IP "\(bu" 4
Travis CI Repository \fIhttps://travis\-ci\.org/TheFox/timr\fR
.
.IP "" 0
.
.SH "BUGS"
Report bugs to
.
.IP "\(bu" 4
the GitHub issues tracker \fIhttps://github\.com/TheFox/timr/issues\fR
.
.IP "\(bu" 4
or via email to \fIchristian@fox21\.at\fR\.
.
.IP "" 0

