.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TIMR\-STOP" "1" "April 2017" "FOX21.at" "Timr Manual"
.
.SH "NAME"
\fBtimr\-stop\fR \- Stop the current running Track\.
.
.SH "SYNOPSIS"
timr stop [\fIoptions\fR]
.
.SH "DESCRIPTION"
Stopps the current running Track and removes it from the Stack\. When more then one Track is on the Stack the left Tracks will not be touched\.
.
.SH "TRACK OPTIONS"
.
.TP
\-m, \-\-message \fImessage\fR
Details about what you have done\. This overwrites the message set on \fBtimr start\fR\. Use \fB\-\-edit\fR option to edit the Start Track message\.
.
.TP
\-\-edit
Edit Track Message\. The EDITOR environment variable must be set\.
.
.TP
\-\-sd, \-\-start\-date \fIdate\fR
Overwrite the Start date\. See timr\-ftime(7)\.
.
.TP
\-\-st, \-\-start\-time \fItime\fR
Overwrite the Start time\. See timr\-ftime(7)\.
.
.TP
\-\-ed, \-\-end\-date \fIdate\fR
End Date\. Default: today\. See timr\-ftime(7)\.
.
.TP
\-\-et, \-\-end\-time \fItime\fR
End Time\. This is useful when you forgot to run the Stop command\. Default: now\. See timr\-ftime(7)\.
.
.TP
\-d, \-\-date \fIdate\fR
\-\-end\-date alias\.
.
.TP
\-t, \-\-time \fItime\fR
\-\-end\-time alias\.
.
.SH "GENERAL OPTIONS"
.
.TP
\-h, \-\-help
Displays the help page\.
.
.SH "EXAMPLES"
.
.nf

timr stop
timr stop \-\-message \'Hello World\'
timr stop \-\-edit
timr stop \-\-time 17:00 \-\-message \'Hello World\'
timr stop \-\-start\-time 10:00 \-\-time 17:00 \e
    \-\-message \'Hello World\'
.
.fi
.
.SH "SEE ALSO"
timr\-start(1), timr\-pop(1), timr\-ftime(7)
.
.SH "TIMR"
This is part of timr(1)\.
