.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TIMR\-START" "1" "April 2017" "FOX21.at" "Timr Manual"
.
.SH "NAME"
\fBtimr\-start\fR \- Start a new Task/Track\.
.
.SH "SYNOPSIS"
timr start [\fIoptions\fR] [\fIid\fR|\fItask_id\fR [\fItrack_id\fR]]
.
.SH "DESCRIPTION"
Always removes all Tracks from the Stack and creates a new Track\. If there is another current running Task this Task will be stopped and removed from the Stack\.
.
.P
Without any options this command always creates a new Task and starts a new Track for this Task\. When providing a Task ID (SHA1 hex) of an existing Task, this Task will be continued\. When also providing a Track ID (SHA1 hex) the same Track message will be taken to create a new Track for the Task\.
.
.SH "TASK OPTIONS"
.
.TP
\-\-id \fIstr\fR
Your ID to identify the Task\. Not just to use the internal Task ID as \fItask_id\fR but also if you like to use your own ID\. For example, when you want to sync Timr with JIRA and use the JIRA IDs to identify Timr Tasks instead of the Timr internal IDs\. This can be any string, but MUST NOT include spaces\. Use this String for \fItask_id\fR\. This ID is also called \'Foreign ID\' by Timr (internal)\.
.
.TP
\-n, \-\-name \fIstr\fR
The name of the new Task\. When providing a \fItask_id\fR this option will be ignored\.
.
.TP
\-\-description \fIstr\fR
Longer description of the new Task\. This should descibe the Task in general\. Provide details by using \fB\-\-message\fR option\. When providing a \fItask_id\fR this option will be ignored\.
.
.TP
\-e, \-\-est, \-\-estimation \fItime\fR
Task Estimation\. See timr\-ftime(7)\.
.
.TP
\-r, \-\-hourly\-rate \fIfloat\fR
Set the Hourly Rate\.
.
.TP
\-\-fr, \-\-flat\-rate, \-\-flat
Has Task a Flat Rate?
.
.SH "TRACK OPTIONS"
.
.TP
\-m, \-\-message \fImessage\fR
Details about what you have done\. This overwrites the \fItrack_id\fR argument\.
.
.TP
\-\-edit
Edit Track Message when providing a \fItrack_id\fR\. The EDITOR environment variable must be set\.
.
.TP
\-d, \-\-date \fIdate\fR
Track Start Date\. Default: today\. See timr\-ftime(7)\.
.
.TP
\-t, \-\-time \fItime\fR
Track Start Time\. This is useful when you forgot to run the Start command\. Default: now\. See timr\-ftime(7)\.
.
.SH "GENERAL OPTIONS"
.
.TP
\-h, \-\-help
Displays the help page\.
.
.SH "ARGUMENTS"
\fItask_id\fR \- Task ID as SHA1 hex string\. It can be the full 40 characters or only the first 6\. If not specified a new Task will be created\.
.
.P
\fItrack_id\fR \- Track ID as SHA1 hex string\. It can be the full 40 characters or only the first 6\. If specified a new Track with the same message will be created\.
.
.SH "EXAMPLES"
.
.nf

timr start
timr start \-\-name my_task1
timr start \-\-name \'Model 101\' \e
    \-\-description \'Construct series 101\.\'
timr start \-\-name my_task3 \e
    \-\-date 2017\-01\-02 \-\-time 15:30 \e
    \-\-message \'Hello World\'
timr start \-\-name my_task4 \-\-message \'Hello World\'
timr start \-\-name my_task5 \-\-estimation 2h
timr start \-\-message \'Hello World\' abcd12
timr start \-\-time 10:30 \-\-message \'Hello World\' abcd12
timr start \-\-id T800
.
.fi
.
.SH "API REFERENCE"
\fIhttps://timr\.fox21\.at/api/TheFox/Timr/Command/StartCommand\.html\fR
.
.SH "SEE ALSO"
timr\-stop(1), timr\-push(1), timr\-ftime(7)
.
.SH "TIMR"
This is part of timr(1)\.
