.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TIMR\-TASK" "1" "April 2017" "FOX21.at" "Timr Manual"
.
.SH "NAME"
\fBtimr\-task\fR \- Show, add, edit, or remove a Task\.
.
.SH "SYNOPSIS"
timr task [show] [\fIoptions\fR] [\fIid\fR|\fItask_id\fR\.\.\.]
.
.P
timr task add [\fIoptions\fR]
.
.P
timr task set [\fIoptions\fR] \fIid\fR|\fItask_id\fR
.
.P
timr task remove \fIid\fR|\fItask_id\fR\.\.\.
.
.SH "DESCRIPTION"
This command takes several subcommands\. Per default, when providing a Task ID it displays details about this specific Task\. Without any arguments it lists all Tasks\.
.
.SH "SUBCOMMANDS"
.
.TP
add
Add a new Task\.
.
.TP
set
Edit an existing Task\.
.
.TP
show
Default when not providing a specific subcommand\.
.
.TP
remove
Delete a Task, all informations about this Task and all including Tracks\. This cannot be undone\.
.
.SH "ADD/SET OPTIONS"
.
.TP
\-\-id \fIstr\fR
Your ID to identify the Task\. Not just to use the internal Task ID as \fItask_id\fR but also if you like to use your own ID\. For example, when you want to sync Timr with JIRA and use the JIRA IDs to identify Timr Tasks instead of the Timr internal IDs\. This can be any string, but MUST NOT include spaces\. Use this String for \fItask_id\fR\. This ID is also called \'Foreign ID\' by Timr (internal)\.
.
.TP
\-n, \-\-name \fIname\fR
Task Name\.
.
.TP
\-\-desc, \-\-description \fIstr\fR
Task Description\.
.
.TP
\-e, \-\-est, \-\-estimation \fItime\fR
Task Estimation\. See timr\-ftime(7)\.
.
.TP
\-b, \-\-billed
Mark Task as billed\.
.
.TP
\-\-unbilled
Mark Task as unbilled\.
.
.TP
\-r, \-\-hourly\-rate \fIfloat\fR
Set the Hourly Rate\.
.
.TP
\-\-no\-hourly\-rate
Unset Hourly Rate\.
.
.TP
\-\-fr, \-\-flat\-rate, \-\-flat
Has Task a Flat Rate?
.
.TP
\-\-no\-flat\-rate, \-\-no\-flat
Unset Flat Rate\.
.
.SH "SHOW OPTIONS"
.
.TP
\-t, \-\-tracks
Show a list of Track IDs for each Task\.
.
.SH "GENERAL OPTIONS"
.
.TP
\-h, \-\-help
Displays the help page\.
.
.SH "EXAMPLES"
.
.nf

timr task
timr task abcd12
timr task show abcd12
timr task set \-\-name \'task_x\' \-\-estimation \'2h 30m\'
timr task set \-\-billed \-\-hourly\-rate 50 \-\-flat\-rate abcd12
timr task set \-\-unbilled \-\-no\-hourly\-rate \-\-no\-flat\-rate abcd12
timr task add \-\-name \'task_z\' \-\-estimation 4h \e
    \-\-hourly\-rate 50 \-\-flat\-rate
timr task add \-\-id T800 \-\-name \'Model 101\'
timr task remove T800
timr task remove abcd12
.
.fi
.
.SH "FOREIGN ID EXAMPLE"
.
.nf

timr task add \-\-id t800 \-\-name Terminator1
timr task set \-\-name Terminator2 t800
timr task remove t800
.
.fi
.
.SH "MAN UNITS"
.
.IP "\(bu" 4
8 hours are 1 man\-day\.
.
.IP "\(bu" 4
5 man\-days are 1 man\-week, and so on\.
.
.IP "" 0
.
.SH "BILLED/UNBILLED"
Set a Task as \fBbilled\fR or \fBunbilled\fR to know which Task you already billed a client\.
.
.P
If a whole Task gets billed/unbilled all Tracks are changed to billed/unbilled\. Each Track has a flag \fBis_billed\fR\.
.
.SH "SEE ALSO"
timr\-track(1), timr\-ftime(7)
.
.SH "TIMR"
This is part of timr(1)\.
