.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TIMR\-STATUS" "1" "April 2017" "FOX21.at" "Timr Manual"
.
.SH "NAME"
\fBtimr\-status\fR \- Show the current Stack\.
.
.SH "SYNOPSIS"
timr status [\fIoptions\fR]
.
.SH "DESCRIPTION"
Displays the Stack as a list and the status of each Track\.
.
.P
To see more details about a specific Task see timr\-task(1), or a specific Track timr\-track(1)\.
.
.SH "OPTIONS"
.
.TP
\-v, \-\-verbose
Show more columns in table view\.
.
.TP
\-f, \-\-full
Show full status\.
.
.TP
\-r, \-\-reverse
Reverse the list\.
.
.TP
\-h, \-\-help
Displays the help page\.
.
.SH "EXAMPLES"
.
.nf

timr status
timr status \-\-full
timr status \-\-full \-\-reverse
.
.fi
.
.SH "API REFERENCE"
\fIhttps://timr\.fox21\.at/api/TheFox/Timr/Command/StatusCommand\.html\fR
.
.SH "SEE ALSO"
timr\-task(1), timr\-track(1)
.
.SH "TIMR"
This is part of timr(1)\.
