.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TIMR" "1" "April 2017" "FOX21.at" "Timr Manual"
.
.SH "NAME"
\fBtimr\fR \- Time Tracking for Hackers\.
.
.SH "SYNOPSIS"
timr [\-V|\-\-version] [\-h|\-\-help] [\-C \fIpath\fR] \fIcommand\fR [\fIargs\fR]
.
.SH "OPTIONS"
.
.TP
\-V, \-\-version
Show version\.
.
.TP
\-h, \-\-help
Show help\.
.
.TP
\-C \fIpath\fR
Set path to the project base directory\. Default: ~/\.timr/defaultc
.
.SH "DESCRIPTION"
Timr is a time tracking tool for the Command\-line, written in Ruby\. You can track your time spent for a specific project\. The main focus of this tool is to use it on the Command\-line and make automatic reports\. All data are stored in YAML files\. So editing can also be done by using your favorite editor\.
.
.SH "COMMANDS"
.
.IP "\(bu" 4
timr\-start(1)
.
.IP "\(bu" 4
timr\-stop(1)
.
.IP "\(bu" 4
timr\-pause(1)
.
.IP "\(bu" 4
timr\-continue(1)
.
.IP "\(bu" 4
timr\-push(1)
.
.IP "\(bu" 4
timr\-pop(1)
.
.IP "\(bu" 4
timr\-status(1)
.
.IP "\(bu" 4
timr\-log(1)
.
.IP "\(bu" 4
timr\-task(1)
.
.IP "\(bu" 4
timr\-track(1)
.
.IP "\(bu" 4
timr\-report(1)
.
.IP "" 0
.
.SH "MISCELLANEOUS"
.
.IP "\(bu" 4
timr\-ftime(7)
.
.IP "" 0
.
.SH "ONLINE RESCOURCES"
.
.IP "\(bu" 4
Homepage \fIhttps://timr\.fox21\.at/\fR
.
.IP "\(bu" 4
API Reference Mainpage \fIhttps://timr\.fox21\.at/api/\fR
.
.IP "\(bu" 4
Man pages \fIhttps://timr\.fox21\.at/man/timr\.1\.html\fR
.
.IP "\(bu" 4
Code Coverage \fIhttps://timr\.fox21\.at/coverage/\fR
.
.IP "\(bu" 4
GitHub Page \fIhttps://github\.com/TheFox/timr\fR
.
.IP "\(bu" 4
RubyGems Page \fIhttps://rubygems\.org/gems/timr\fR
.
.IP "\(bu" 4
Travis CI Repository \fIhttps://travis\-ci\.org/TheFox/timr\fR
.
.IP "" 0
.
.SH "BUGS"
Report bugs to
.
.IP "\(bu" 4
the GitHub issues tracker \fIhttps://github\.com/TheFox/timr/issues\fR
.
.IP "\(bu" 4
or via email to \fIchristian@fox21\.at\fR\.
.
.IP "" 0
.
.SH "AUTHOR"
Timr was created by Christian Mayer\.
.
.SH "COPYRIGHT"
Copyright (C) 2016 Christian Mayer \fIhttps://fox21\.at\fR
.
.P
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\.
.
.P
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\. See the GNU General Public License for more details\. You should have received a copy of the GNU General Public License along with this program\. If not, see \fIhttp://www\.gnu\.org/licenses/\fR\.
