.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TIMR\-TRACK" "1" "April 2017" "FOX21.at" "Timr Manual"
.
.SH "NAME"
\fBtimr\-track\fR \- Show, add, edit, move, or remove a Track\.
.
.SH "SYNOPSIS"
timr track \fIsubcommand\fR [\fIoptions\fR] [\fItrack_id\fR]
.
.SH "DESCRIPTION"
This command takes several subcommands\. Per default, when providing a Track ID it displays details about this specific Track\.
.
.SH "SUBCOMMANDS"
.
.TP
add
Add a new Track\.
.
.TP
set
Edit an existing Track\. To move a Track to another Task see \fB\-\-task\fR option in section SET OPTIONS\.
.
.TP
show
Default when not providing a specific subcommand\.
.
.TP
remove
Delete a Track and all informations about this Track\. This cannot be undone\.
.
.SH "ADD/SET OPTIONS"
.
.TP
\-m, \-\-message \fImessage\fR
Track Message\. Details about what you have done\.
.
.TP
\-\-sd, \-\-start\-date \fIdate\fR
Start Date
.
.TP
\-\-st, \-\-start\-time \fItime\fR
Start Time
.
.TP
\-\-ed, \-\-end\-date \fIdate\fR
End Date
.
.TP
\-\-et, \-\-end\-time \fItime\fR
End Time
.
.TP
\-b, \-\-billed
Mark Track as billed\.
.
.TP
\-\-unbilled
Mark Track as unbilled\.
.
.SH "SET OPTIONS"
\-\-task \fItask_id\fR: Move Track to another Task\. \fItask_id\fR can also be a Foreign ID\. See \fBtimr\-task(1)\fR\.
.
.SH "SHOW OPTIONS"
.
.TP
\-t, \-\-task
Show Task of Track\. Same as \fBtimr task <task_id>\fR\.
.
.SH "GENERAL OPTIONS"
.
.TP
\-h, \-\-help
Displays the help page\.
.
.SH "EXAMPLES"
.
.nf

timr track abcd12
timr track show abcd12
timr track set \-\-start\-date 2017\-01\-01 \-\-start\-time 10:00 \e
    \-\-end\-date 2017\-01\-02 \-\-end\-time 15:30 abcd12
timr track set \-\-track xyz345 abcd12
timr track add \-\-start\-date 2017\-01\-02 \-\-start\-time 16:00 \e
    \-\-end\-date 2017\-01\-02 \-\-end\-time 17:00 xyz345
timr track remove abcd12
.
.fi
.
.SH "DATETIME FORMATS"
.
.TP
\fIdate_time\fR
A DateTime is one single string representing \fB<date> <time>\fR\.
.
.TP
\fIdate\fR
Formats: \fBYYYY\-MM\-DD\fR, \fBMM/DD/YYYY\fR, \fBDD\.MM\.YYYY\fR
.
.TP
\fItime\fR
Formats: \fBHH:MM\fR, \fBHH:MM:SS\fR
.
.P
See \fBtimr\-task(1)\fR, section ESTIMATION for estimation \fItime\fR details\.
.
.SH "ONLINE RESCOURCES"
.
.IP "\(bu" 4
Homepage \fIhttps://timr\.fox21\.at/\fR
.
.IP "\(bu" 4
Code Coverage \fIhttps://timr\.fox21\.at/coverage/\fR
.
.IP "\(bu" 4
GitHub Page \fIhttps://github\.com/TheFox/timr\fR
.
.IP "\(bu" 4
RubyGems Page \fIhttps://rubygems\.org/gems/timr\fR
.
.IP "\(bu" 4
Travis CI Repository \fIhttps://travis\-ci\.org/TheFox/timr\fR
.
.IP "" 0
.
.SH "BUGS"
Report bugs to
.
.IP "\(bu" 4
the GitHub issues tracker \fIhttps://github\.com/TheFox/timr/issues\fR
.
.IP "\(bu" 4
or via email to \fIchristian@fox21\.at\fR\.
.
.IP "" 0

