before_script:
    - apt-get update -yqq
    - 'which ssh-agent || ( apt-get install openssh-client -y )'
    - 'which rsync || ( apt-get install rsync -yqq --force-yes )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ruby -v
    - gem update --system
    - gem install bundler -v '~>1.13'
    - gem install ronn -v '0.7.3'
    - bundler --version
    - bundler install

stages:
    - test
    - release
    - deploy

test_feature:
    image: ruby:2.1
    stage: test
    environment: test
    only:
        - /^feature/
    script:
        - ./bin/test.sh

test_21:
    image: ruby:2.1
    stage: test
    environment: test
    only:
        - tags
    script:
        - ./bin/test.sh

test_22:
    image: ruby:2.2
    stage: test
    environment: test
    only:
        - tags
    script:
        - ./bin/test.sh

test_23:
    image: ruby:2.3
    stage: test
    environment: test
    only:
        - tags
    script:
        - ./bin/test.sh

test_24:
    image: ruby:2.4.0
    stage: test
    environment: test
    only:
        - tags
    script:
        - ./bin/test.sh

release:
    image: ruby:2.4.0
    stage: release
    environment: gem
    only:
        - tags
    script:
        - mkdir -p ~/.gem
        - 'printf "%s\n:rubygems_api_key: %s" "---" "${RUBYGEMSORG_API_KEY}" > ~/.gem/credentials; chmod 0600 ~/.gem/credentials'
        - ./bin/release.sh

deploy_dev:
    image: ruby:2.4.0
    stage: deploy
    environment: homepage_dev
    only:
        - develop
    script:
        - ./bin/build.sh
        - ./bin/publish

deploy_prod:
    image: ruby:2.4.0
    stage: deploy
    environment: homepage_prod
    only:
        - tags
    script:
        - ./bin/build.sh
        - ./bin/publish
