language: ruby
rvm:
    - 2.1
    - 2.2
    - 2.3
    - 2.4.0
    - ruby-head
sudo: required
before_install:
    - gem --version
    - gem update --system
    - gem install bundler -v '~>1.13'
    - bundler --version
install:
    - bundler install
    - 'gem build "${GEMSPEC_FILE}"'
    - 'gem install "${GEM_NAME}"-*.gem'
    - 'gem list -l "${GEM_NAME}"'
script:
    - ./bin/test.sh
    - cd
    - which -a timr
    - timr --version
